# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0e495a5bd5b4abc80c211ecf33ed4c9c6c4967f735afadc27bc1b3b9cd19a6f095629d6efc1025d09813b26ea666b62dd35c91a0864d47c92a263d78278a7ad

test:
  secret_key_base: 286dd16c027abde44222353bbbbd1f0d93394def824811ab5a8707c28cca905182f81f2fbb4f8986dfeb179f9b659b39145c81d9bcbdaf98e79571acdc66fd0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
