# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendshipApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
