# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendshipApp', '0002_friendship_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='_user_friend_+', to='friendshipApp.User'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
