# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 363be22efbccaede17691195abd79bebb748c307fa0d12651d4685b9fa0b273fccbfdbb97ca4665dd6daa7e4e99fd64777d6c0407e598e23945cd2e8d0f78cd7

test:
  secret_key_base: a7ee26772392b91055cc7ac53953dbc0a203c46b7b8fefd22c5bc264d5f782ec08803f2ed2b810b8745312d2c4724d50afdab922a75dd7a9addf61f30e328809

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
