# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userValidation', '0002_auto_20170419_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='username',
        ),
    ]
