# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2fb201f4bc438ae3c656e866a471f3c20b089d6060dc6cbd5b8b98fdf76202951280d1c851b18b34b67f5e95159e007bde4f2fafcb90481de93800728a7160d

test:
  secret_key_base: 628e1c990f1279dc1c0dc6842e14226a708947821c978a3b03e3e2ae56b550f16fbc107f0d7e3ec2909c5eb7ecfa6e9ebebbda5843da59783ce9fcd4077a6ff2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
