# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appt_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appt_time',
            field=models.TimeField(),
        ),
    ]
