# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc8995d93df5f1a9009b907d7d8344833317f3c8d8e3e876f16ec3d8bb4f2ab0dafa5028adcc4d3d55f3296dc8b06020a638b2302192e9ff3044ec9585f351e9

test:
  secret_key_base: 57dead101c6758e97fba7e549d0f1163fc6b0fd64f5c31cb72c6adb26f5fa2086b10de967bae0716e73537705289dd261c7b38cf93b8bf8d43048cf93a075d06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
